### ISSUE TITLE
-SkipDuplicate

### ISSUE THREAD

**Issue by sieukrem** [NuGet/docs.microsoft.com-nuget.de-de#14]
This parameter is not recognized by the nuget push command

The help output of nuget push does not mention SkipDuplicate also

NuGet Version: 4.9.3.5777
usage: NuGet &lt;command&gt; [args] [options]
Type 'NuGet help &lt;command&gt;' for help on a specific command.

Please fix the docu and the tool. I need this parameter

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fea0203e-9793-5e92-ee94-0bf972ff91cc
* Version Independent ID: 6d98cff6-9ef7-8c84-941b-4db0db65908c
* Content: [NuGet-CLI-Push-Befehl](https://docs.microsoft.com/de-de/nuget/tools/cli-ref-push#feedback)
* Content Source: [docs/tools/cli-ref-push.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/tools/cli-ref-push.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@donnie-msft can you take a look?

**Comment by donnie-msft** [comment]
@sieukrem SkipDuplicate is available starting with NuGet Version 5.1. Apologies that the docs weren't clear, and I recently submitted a PR to update them accordingly, which is pending approvals now: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1470

**Comment by sieukrem** [comment]
Thanks!
