### ISSUE TITLE
Option names must not be translated

### ISSUE THREAD

**Issue by KGuetter** [NuGet/docs.microsoft.com-nuget.de-de#15]
In the German translation of this page, e.g. the option "-PreRelease" is incorrectly translated as "-Vorab", and "-IncludeDelisted" as "-Incluentdelisted". Option names must not be translated.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7387ab78-ea68-638b-37fa-e3e0b567bd34
* Version Independent ID: 2050c175-26f2-bd31-174d-84661f7ab845
* Content: [Befehl ](https://docs.microsoft.com/de-de/nuget/reference/cli-reference/cli-ref-list#feedback)
* Content Source: [docs/reference/cli-reference/cli-ref-list.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/cli-reference/cli-ref-list.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by srvbpigh** [comment]
Hello, @KGuetter
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KGuetter 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/nuget/reference/cli-reference/cli-ref-list#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
