### ISSUE TITLE
Translation of Tags not useful

### ISSUE THREAD

**Issue by milbrandt** [NuGet/docs.microsoft.com-nuget.de-de#6]
Translation of tags in the documentation `summary`= Zusammenfassung or `description`=Beschreibung are not helpful, as I the German translations will not be recogniced by nuget.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [NuSpec-Dateireferenz für NuGet](https://docs.microsoft.com/de-de/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/nuspec.md)
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by LisandroSu** [comment]
Hello, @milbrandt ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @milbrandt 

Thank you for your patience. We are still working on this file as this is a bigger issue that we expected.

We will let you know when the changes are made on our side.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @milbrandt ,
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/nuget/reference/nuspec#feedback. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
