### ISSUE TITLE
What's the point of -Force / -NoCache if it checks existing data anyway?

### ISSUE THREAD

**Issue by taori** [NuGet/docs.microsoft.com-nuget.de-de#8]
Using this command: nuget restore solutionname.sln -Force -NoCache

i keep getting "Assets file has not changed. Skipping assets file writing." I am attempting to restore my solution packages using this command to bypass the awfully tedious process of patching a multi project solution template to load my nuget references.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d63170c3-1894-8ead-b557-9937dae88172
* Version Independent ID: 67968c11-0aa0-f835-357d-8690911eb011
* Content: [NuGet-CLI-Befehl ](https://docs.microsoft.com/de-de/nuget/tools/cli-ref-restore)
* Content Source: [docs/tools/cli-ref-restore.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/tools/cli-ref-restore.md)
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment]
Hello, @taori 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
