### ISSUE TITLE
Getting a multi project solution with nuget references seems to be way more effort than it could be

### ISSUE THREAD

**Issue by taori** [NuGet/docs.microsoft.com-nuget.de-de#9]
Are there any plans of making this an easy process? To me it seems like the "export project template" functionality could streamline the whole process of packaging + adding nuget references. Due to the great effort which has to be put into getting a working solution template this is a major roadblock. After spending about 8 hours of figuring out several issues with creating a template i am now at the point of figuring out how to get this working with nuget packages.

There were several times during this process where i thought "hm maybe i should write a tool to convert my project into a project which has working references" - this is an indicator that this area of VS could use some love.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bbf9be6a-e7b0-b9b6-a3e8-8b5de3c6900d
* Version Independent ID: c12505c9-6f14-7111-2578-5c2664b4515d
* Content: [NuGet-Pakete in Visual Studio-Vorlagen](https://docs.microsoft.com/de-de/nuget/visual-studio-extensibility/visual-studio-templates)
* Content Source: [docs/visual-studio-extensibility/Visual-Studio-Templates.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/visual-studio-extensibility/Visual-Studio-Templates.md)
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment]
Hello, @taori 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

@JasonCard FYI
